

name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ymphyow/my_portfolio- .
      
      - name: Push image 
        run: docker login -u ymphyow -p ${{secrets.REGISTRY_PASS}}
             docker push ymphyow/my_portfolio-

    
