

name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ymphyow/portfolio .
        #run: docker build ${{secrets.REGISTRY_USER}}/portfolio:${{github.run_number}} .
         
      
      - name: Push image 
        run: docker login -u ymphyow -p ${{secrets.REGISTRY_PASS}}
             docker push ymphyow/portfolio

    
